// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwNPunH5GwF_MaJft8dGMZh7-jl0nMmTM',
    appId: '1:916169609528:web:38ca8da33a9d61e0c6f1cd',
    messagingSenderId: '916169609528',
    projectId: 'ethiscan-mse',
    authDomain: 'ethiscan-mse.firebaseapp.com',
    storageBucket: 'ethiscan-mse.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuJnOglnnntUBAa_EJN8K0Rlp791Xs-zk',
    appId: '1:916169609528:android:5f6d420dd600ad39c6f1cd',
    messagingSenderId: '916169609528',
    projectId: 'ethiscan-mse',
    storageBucket: 'ethiscan-mse.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8cxQdlu-220lLKG5gEIvZYj3LBezXQbQ',
    appId: '1:916169609528:ios:ead43268fcaa4701c6f1cd',
    messagingSenderId: '916169609528',
    projectId: 'ethiscan-mse',
    storageBucket: 'ethiscan-mse.appspot.com',
    iosBundleId: 'com.example.ethiscan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8cxQdlu-220lLKG5gEIvZYj3LBezXQbQ',
    appId: '1:916169609528:ios:ead43268fcaa4701c6f1cd',
    messagingSenderId: '916169609528',
    projectId: 'ethiscan-mse',
    storageBucket: 'ethiscan-mse.appspot.com',
    iosBundleId: 'com.example.ethiscan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwNPunH5GwF_MaJft8dGMZh7-jl0nMmTM',
    appId: '1:916169609528:web:3216865a0c6bfa83c6f1cd',
    messagingSenderId: '916169609528',
    projectId: 'ethiscan-mse',
    authDomain: 'ethiscan-mse.firebaseapp.com',
    storageBucket: 'ethiscan-mse.appspot.com',
  );
}