# This is a basic workflow to help you get started with Actions
name: CD - Create a new release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
      - "v*.*.*" # on every version tag will build a new android artifact.
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.19.3"

      - name: Pub Get Packages
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release
          
      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: EthiScan release ${{ github.ref_name }}
          files: | 
            build/app/outputs/apk/release/*.apk
      
      - name: Rename APK and Send to Telegram Group
        run: |
          TAG_NAME=${GITHUB_REF/refs\/tags\//}
          APK_PATH=$(ls build/app/outputs/apk/release/*.apk)
          NEW_APK_PATH="build/app/outputs/apk/release/ethiscan_${TAG_NAME}.apk"
          mv "$APK_PATH" "$NEW_APK_PATH"
          MESSAGE="🚀 New release of EthiScan available! Version: $TAG_NAME"
          curl -F chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
               -F document=@"$NEW_APK_PATH" \
               -F caption="$MESSAGE" \
               https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument
        env:
          GITHUB_REF: ${{ github.ref }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
